import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {gzipSync} from 'node:zlib';
import {build} from 'esbuild';
import {QuestionBank} from '../server/question-bank.mjs';
import {decodeImport,mergeEvents} from './validation.mjs';
const root=fileURLToPath(new URL('../..',import.meta.url));
const args=process.argv.slice(2),option=name=>{const i=args.indexOf(name);return i<0?null:args[i+1];};
const out=path.resolve(option('--out')||path.join(root,'.gre-platform/GRE-platform-offline.html'));
const pdfDir=option('--pdf-dir');
const tracked=execFileSync('git',['ls-files','-z'],{cwd:root,encoding:'utf8'}).split('\0').filter(Boolean);
const files={};
for(const file of tracked){if(file==='profile.md'||file==='materials/catalog.yaml'||/^vocab\/(lexicon\.json|relations\.json|difficult\.yaml|mastered\.yaml|homework\/[^/]+\.(json|md))$/.test(file)||/^(verbal|quant|analytical-writing)\/submissions\/[^/]+\.md$/.test(file)||/^platform\/events\/[^/]+\.json$/.test(file)){try{files[file]=await fs.readFile(path.join(root,file),'utf8');}catch(e){if(e.code!=='ENOENT')throw e;files[file]=execFileSync('git',['show',`HEAD:${file}`],{cwd:root,encoding:'utf8',maxBuffer:20*1024*1024});}}}
const baseEvents=Object.entries(files).filter(([p])=>p.startsWith('platform/events/')).map(([,s])=>JSON.parse(s));
const temp=await fs.mkdtemp(path.join(os.tmpdir(),'gre-offline-build-'));
let questions=[];
try{const bank=new QuestionBank(temp);for(const [id,start,fallback,short] of [['text_completion_2000',14,'张巍GRE填空机经2000题.pdf','tc.pdf'],['reading_440',22,'张巍GRE阅读机经440篇.pdf','reading.pdf'],['quant_900',4,'张巍GRE最新数学机经900题 .pdf','quant.pdf']]){const filename=pdfDir?path.join(pdfDir,short):path.join(root,'materials/files',fallback);const stat=await fs.stat(filename);const q=await bank.build(id,filename,start,`offline-${stat.size}-${stat.mtimeMs}`);questions.push(...q);console.log(`${id}: ${q.length} questions, ${q.filter(x=>x.native).length} native text`);}}finally{await fs.rm(temp,{recursive:true,force:true});}
let initial_events=[],ui={};
if(option('--import')){const data=JSON.parse(await fs.readFile(option('--import'),'utf8'));const imported=decodeImport(data),merged=mergeEvents(baseEvents,imported.events);const ids=new Set(baseEvents.map(e=>e.id));initial_events=merged.events.filter(e=>!ids.has(e.id));const map=new Map(questions.map(q=>[q.key,q]));for(const q of imported.questions){const found=map.get(q.key);if(found&&(found.prompt!==q.prompt||JSON.stringify(found.options)!==JSON.stringify(q.options)))throw Error('Imported question differs from the source PDF: '+q.key);if(!found)map.set(q.key,q);}questions=[...map.values()];if(data.format==='gre-offline-answers'){const drafts={};for(const [key,d]of Object.entries(data.session.drafts||{})){if(!map.has(key))continue;drafts[key]={answer:(d.selected||[]).join('/'),note:d.note||'',saved:initial_events.some(e=>e.id===d.savedId)||baseEvents.some(e=>e.id===d.savedId),attemptId:d.savedId||randomUUID()};}ui['gre:practice:v3']=JSON.stringify({type:'se',active:{},drafts});}console.log(`Imported ${initial_events.length} real events with original IDs and timestamps.`);}
const pack={schema_version:1,repository:'zehouzhang0-lang/gre-data',commit:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),built_at:new Date().toISOString(),files,questions,initial_events,ui};
const compat=(await fs.readFile(path.join(root,'platform/offline/compat.mjs'),'utf8')).replace('export function','function')+'\ninstallBrowserCompat();\n';
const bootstrap=`import {boot} from './boot.mjs'; await boot(); await import('./OfflineApp.jsx');`;
const web=path.join(root,'platform/web/src');
const result=await build({stdin:{contents:bootstrap,resolveDir:path.join(root,'platform/offline'),sourcefile:'offline-entry.mjs',loader:'js'},bundle:true,write:false,outdir:'out',format:'esm',platform:'browser',target:'es2022',minify:true,jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'offline-adapters',setup(b){b.onResolve({filter:/^node:(fs\/promises|path|crypto)$/},a=>({path:path.join(root,'platform/offline',{'node:fs/promises':'virtual-files.mjs','node:path':'browser-path.mjs','node:crypto':'browser-crypto.mjs'}[a.path])}));b.onResolve({filter:/^\.\/api$/},a=>a.importer.startsWith(web)?{path:path.join(root,'platform/offline/runtime.mjs')}:null);b.onResolve({filter:/pdf\.worker\.min\.mjs\?url$/},()=>({path:path.join(root,'node_modules/pdfjs-dist/build/pdf.worker.min.mjs'),namespace:'inline-worker'}));b.onLoad({filter:/.*/,namespace:'inline-worker'},async a=>({contents:`export default URL.createObjectURL(new Blob([${JSON.stringify(compat+await fs.readFile(a.path,'utf8'))}],{type:'text/javascript'}));`,loader:'js'}));b.onLoad({filter:/platform\/web\/src\/.*\.(jsx|js)$/},async a=>{let s=await fs.readFile(a.path,'utf8');if(/\blocalStorage\b/.test(s)){s=`import {offlineStorage} from ${JSON.stringify(path.join(root,'platform/offline/storage.mjs'))};\n`+s.replace(/\blocalStorage\b/g,'offlineStorage');}return {contents:s,loader:a.path.endsWith('jsx')?'jsx':'js',resolveDir:path.dirname(a.path)};});}}]});
const js=result.outputFiles.find(x=>x.path.endsWith('.js')).text,css=result.outputFiles.find(x=>x.path.endsWith('.css'))?.text||'';
const safe=s=>s.replace(/<\/script/gi,'<\\/script');
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="color-scheme" content="light"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' blob:; worker-src blob:; style-src 'unsafe-inline'; img-src data: blob:; connect-src blob:; font-src data: blob:; base-uri 'none'; form-action 'none'"><title>GRE 学习工作台 · 离线版</title><style>${css}</style></head><body><div id="root"><p style="padding:30px">正在打开离线学习工作台…</p></div><noscript>请下载文件并用支持 JavaScript 的浏览器打开。</noscript><script id="offline-pack" type="application/octet-stream">${gzipSync(JSON.stringify(pack)).toString('base64')}</script><script id="offline-restore" type="application/json">null</script><script type="module">${safe(js)}</script></body></html>`;
await fs.mkdir(path.dirname(out),{recursive:true});await fs.writeFile(out,html);console.log(JSON.stringify({out,bytes:Buffer.byteLength(html),questions:questions.length,baselineEvents:baseEvents.length,importedEvents:initial_events.length}));
