import React,{useEffect,useState,useRef,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import Practice from '../web/src/Practice';
import Vocabulary from '../web/src/Vocabulary';
import WordRelations from '../web/src/WordRelations';
import Recall from '../web/src/Recall';
import History from '../web/src/History';
import {Icon,Modal} from '../web/src/components';
import OfflineLibrary from './OfflineLibrary';
import {request,backup,download,exportHTML,importBackup,allQuestions,initialWarning} from './runtime.mjs';
import {storageMessage,persist} from './storage.mjs';
import {createRefreshQueue} from '../shared/refresh-queue.mjs';
import '../web/src/styles.css';
import './offline.css';
function App(){const [state,setState]=useState(null),[page,setPage]=useState('practice'),[error,setError]=useState(initialWarning),[toast,setToast]=useState(''),[relationSearch,setRelationSearch]=useState(''),[recallWords,setRecallWords]=useState(null),[transfer,setTransfer]=useState(false),[busy,setBusy]=useState(false),[cacheStatus,setCacheStatus]=useState(storageMessage),[generation,setGeneration]=useState(0),[copyText,setCopyText]=useState('');const revision=useRef(''),queue=useRef(null);if(!queue.current)queue.current=createRefreshQueue(async()=>{const s=await request('/api/state?revision='+revision.current);if(!s.unchanged){revision.current=s.revision;setState(s);}});const refresh=useCallback(()=>queue.current.refresh(),[]);
useEffect(()=>{refresh().catch(e=>setError(e.message));const timer=setInterval(()=>{if(!document.hidden)queue.current.poll().catch(e=>setError(e.message));},60000);const storage=()=>setCacheStatus(storageMessage),exportNow=()=>setTransfer(true),visible=()=>{if(!document.hidden)queue.current.poll().catch(e=>setError(e.message));};window.addEventListener('gre:storage',storage);window.addEventListener('gre:export',exportNow);document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);window.removeEventListener('gre:storage',storage);window.removeEventListener('gre:export',exportNow);document.removeEventListener('visibilitychange',visible);};},[refresh]);useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);},[toast]);
async function restore(file){if(!file)return;setBusy(true);try{if(file.size>50*1024*1024)throw Error('JSON 文件最大 50 MB');const result=await importBackup(JSON.parse(await file.text()));revision.current='';await refresh();setGeneration(v=>v+1);setToast(`已导入 ${result.added} 条新记录、${result.questions} 道题；相同编号不会重复计数。`);}catch(e){setError(e.message);}finally{setBusy(false);}}
function exportJSON(){persist();download('GRE-platform-records-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json',backup(true));setToast('已发起下载，请到手机“下载”目录确认文件。');}
const nav=[['practice','file','刷题练习'],['library','folder','资料库'],['vocab','book','生词本'],['relations','cards','分类与关联'],['recall','cards','记忆与背诵'],['history','history','学习记录']],props={state,refresh,notify:setToast};return <div className="app"><aside className="sidebar"><div className="brand"><strong>GRE</strong><span>学习工作台 · 离线版</span></div><nav aria-label="主导航">{nav.map(([id,icon,name])=><button key={id} className={page===id?'active':''} aria-current={page===id?'page':undefined} onClick={()=>{setPage(id);if(id==='relations')setRelationSearch('');if(id==='recall')setRecallWords(null);}}><Icon name={icon}/><span>{name}</span></button>)}</nav><div className="sidebar-bottom"><div className="target"><span>目标分数</span><strong>{state?.target??'—'}</strong></div><button className="sync-button" onClick={()=>setTransfer(true)}><Icon name="sync"/>导入 / 导出</button><small>离线使用 · 文件备份</small></div></aside><main><div className="offline-status"><span>{cacheStatus}</span><button className="text-button" onClick={exportJSON}>导出记录</button></div>{error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>setError('')}>关闭提示</button></div>}{!state?<div className="loading">正在准备离线学习数据…</div>:<>{page==='practice'&&<Practice key={generation} {...props}/>}{page==='library'&&<OfflineLibrary {...props}/>}{page==='vocab'&&<Vocabulary {...props} openRelations={word=>{setRelationSearch(word||'');setPage('relations');}} startRecall={words=>{setRecallWords(words);setPage('recall');}}/>}{page==='relations'&&<WordRelations {...props} initialSearch={relationSearch} back={()=>setPage('vocab')} startRecall={words=>{setRecallWords(words);setPage('recall');}}/>}{page==='recall'&&<Recall {...props} initialWords={recallWords}/>}{page==='history'&&<History {...props}/>}</>}</main>{toast&&<div className="toast" role="status">{toast}</div>}{transfer&&<Modal title="导入 / 导出学习记录" onClose={()=>setTransfer(false)}><p>已内置 {allQuestions().length} 道题的定位与可提取原文、{state?.vocabulary.length||0} 个词条。数学图表和特殊排版题请在资料库连接对应 PDF。</p><p>当前有 {backup().events.length} 条离线记录需要随文件保留。JSON 包含作答原文、题目和选项；发回聊天后可进行完整讲解。</p><div className="offline-actions"><button className="primary" onClick={exportJSON}>下载学习记录 JSON</button><button onClick={()=>{exportHTML();setToast('已发起 HTML 下载，PDF 不包含在内；请确认文件下载完成。');}}>下载带记录的 HTML</button><label className="button">{busy?'正在导入…':'导入记录 / 题包 JSON'}<input className="file-input" type="file" accept=".json,application/json" disabled={busy} onChange={e=>{restore(e.target.files[0]);e.target.value='';}}/></label></div><details><summary>下载失败时复制记录</summary><button onClick={()=>setCopyText(JSON.stringify(backup(true)))}>生成可复制文本</button>{copyText&&<textarea aria-label="备份 JSON 文本" readOnly rows="8" value={copyText} onFocus={e=>e.target.select()}/>}</details><p className="muted">导出不会自动上传 GitHub。导入按原记录编号合并；草稿、翻页和查看记录不会增加作答次数。新 HTML 保留草稿和已提交记录，PDF 需要重新选择。离线版不连接 AI。</p></Modal>}</div>;}
createRoot(document.getElementById('root')).render(<App/>);
