import {validate,keyOf} from '../server/store.mjs';
export function canonical(v){if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';if(v&&typeof v==='object')return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';return JSON.stringify(v);}
export function checkEvent(raw){if(!raw||raw.schema_version!==1||typeof raw.id!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(raw.id)||!Number.isFinite(Date.parse(raw.recorded_at)))throw Error('作答记录编号或日期无效');validate(raw.kind,raw.payload);if(raw.kind==='vocab_session'&&(!Array.isArray(raw.payload.items)||raw.payload.items.length!==raw.payload.words.length))throw Error('词汇轮次缺少题目快照');return {schema_version:1,id:raw.id,kind:raw.kind,recorded_at:raw.recorded_at,payload:structuredClone(raw.payload)};}
export function checkQuestion(q){if(!q||!['tc','se','rc','quant'].includes(q.type)||typeof q.material!=='string'||typeof q.unit!=='string'||typeof q.question!=='string'||keyOf(q)!==q.key)throw Error('题包中的题目定位无效');if(q.prompt!==undefined&&(typeof q.prompt!=='string'||q.prompt.length>20000))throw Error('题干格式无效');if(q.options!==undefined&&(!Array.isArray(q.options)||q.options.length>12||q.options.some(o=>typeof o!=='string'||o.length>10000)))throw Error('选项格式无效');return structuredClone(q);}
export function decodeImport(data){if(data?.format==='gre-offline-answers'){if(!Array.isArray(data.questions)||!Array.isArray(data.session?.records))throw Error('旧版作答文件不完整');const questions=data.questions.map(checkQuestion),map=new Map(questions.map(q=>[q.key,q]));const events=data.session.records.map(raw=>{const event=checkEvent(raw),q=map.get(raw.question_key);if(event.kind!=='attempt'||!q||keyOf(event.payload)!==q.key)throw Error('作答与题目不匹配');if(q.type==='se'){const letters=event.payload.answer.split('/');if(letters.length!==2||new Set(letters).size!==2||letters.some(l=>!q.letters.includes(l)))throw Error('SE 答案必须是两个不同选项');}return event;});return {events,questions};}
 if(data?.format==='gre-platform-offline-backup'&&data.schema_version===1){if(!Array.isArray(data.events)||!Array.isArray(data.questions))throw Error('离线备份不完整');return {events:data.events.map(checkEvent),questions:data.questions.map(checkQuestion)};}
 if(data?.format==='gre-question-pack'&&data.schema_version===1&&Array.isArray(data.questions))return {events:[],questions:data.questions.map(checkQuestion)};
 throw Error('请选择离线版导出的 JSON、旧版14题作答 JSON 或 GRE 题包');}
export function mergeEvents(existing,incoming){const map=new Map(existing.map(e=>[e.id,e]));let added=0;for(const e of incoming){const old=map.get(e.id);if(old&&canonical(checkEvent(old))!==canonical(e))throw Error(`记录 ${e.id} 内容冲突，未导入任何记录`);if(!old){map.set(e.id,e);added++;}}return {events:[...map.values()].sort((a,b)=>a.recorded_at.localeCompare(b.recorded_at)||a.id.localeCompare(b.id)),added};}
